### ISSUE TITLE
Bugs?

### ISSUE THREAD

**Issue by peterfromthehill** [silentsakky/zarafa-webapp-passwd#1]
Hi,

first - thank you for your work! Great Job!
I must do some stuff to make your plugin working for me.

All "Bugs" are in the saveInLDAP function.
You use in the search $uid - but there is no $uid.
I but $uid = $data['username']; at the begining.

next is the ldap_set_options... you use $ds.. there is no $ds.. -> $ldapconn.

from now.. it works.. _but_ if you change the password.. webapp kick you out.. why? now is your login pw wrong... so i fix it with:

> if (ldap_errno($ldapconn) === 0) {
>  session_start();
>  $_SESSION['password'] = $data['new_password'];
>  session_write_close();
>  $this->sendFeedback(true, array(

from now it works for me very well.. thank you :) 

one questen.. what goes up with sugarcrm in injectPluginSettings? C&P? :D

best regards

Michael Haupt

**Comment by silentsakky** [comment]
no updates on this, assuming all issues are fixed
