### ISSUE TITLE
Plugin does not work where web server is not hosted on same zarafa server

### ISSUE THREAD

**Issue by mcost** [silentsakky/zarafa-webapp-passwd#10]
I have installed the plugin and it didn't work for me.

My setup is such that I have the web server on a different server as the zarafa server (as recommended for max performance).

In the module class.passwdmodule.php there is no option --host passed to the zarafa-password command hence the issue.

I have temporarily solved my own issue by hacking the plugin to include the hostname and port, i.e.                         
$passwd_cmd = '/usr/bin/zarafa-passwd -h https://mrc-zfr1:237 -u %s -o %s -p %s';

but clearly this is a hack that only works for me.

**Comment by silentsakky** [comment]
this plugin is not using zarafa-passwd any more it is using mapi_zarafa_setuser to change password

**Comment by mcost** [comment]
great! that's fantastic news. Thanks a lot.
