### ISSUE TITLE
Zarafa Webapp 2.02 supported?

### ISSUE THREAD

**Issue by RogerSik** [silentsakky/zarafa-webapp-passwd#12]
Hello,

is Zarafa Webapp 2.02 supported? 

I downloaded and installed the plugin but this plugins doens't is visible under plugins on the webinterface.

**Comment by mcost** [comment]
The previous version did work for me and I am still using it. 

You need to make sure you enable it in its config.php file. 

Marco 

On 29 June 2015 06:33:21 BST, Roger <notifications@github.com> wrote:
>Hello,
>
>is Zarafa Webapp 2.02 supported? 
>
>I downloaded and installed the plugin but this plugins doens't is
>visible under plugins on the webinterface.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/silentsakky/zarafa-webapp-passwd/issues/12
>-- 
>This message has been scanned for viruses and
>dangerous content by MailScanner, and is
>believed to be clean.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by RogerSik** [comment]
Hello,

it is enabled under config.php.

Other plugins are working well only these plugin is not showing under plugins.
________________________________
Von: mcost<mailto:notifications@github.com>
Gesendet: ‎29.‎06.‎2015 09:52
An: silentsakky/zarafa-webapp-passwd<mailto:zarafa-webapp-passwd@noreply.github.com>
Cc: Roger Sikorski<mailto:roger@sikorski.cc>
Betreff: Re: [zarafa-webapp-passwd] Zarafa Webapp 2.02 supported? (#12)

The previous version did work for me and I am still using it.

You need to make sure you enable it in its config.php file.

Marco

On 29 June 2015 06:33:21 BST, Roger <notifications@github.com> wrote:
>Hello,
>
>is Zarafa Webapp 2.02 supported?
>
>I downloaded and installed the plugin but this plugins doens't is
>visible under plugins on the webinterface.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/silentsakky/zarafa-webapp-passwd/issues/12
>--
>This message has been scanned for viruses and
>dangerous content by MailScanner, and is
>believed to be clean.

--
Sent from my Android device with K-9 Mail. Please excuse my brevity.
--
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by mcost** [comment]
To get it to work I have copied the config file into:

 
\etc\zarafa\webapp\config-passwd.php

 

And set it to enabled and this shows up in 2.02

 
The version I am using of the plugin is:

 
 <version>1.0</version>                  

 
 Note that I am using it under Fedora 21, not sure which operating system your are using?

 
Marco

 
-----Original message-----

**Comment by RogerSik** [comment]
﻿Hi,

i'm using Ubuntu Server 14.04.

The plugin is installed under /usr/share/zarafa-webapp/plugins and now the configuration file under /etc/zarafa/webapp/

But this also doens't show the plugin. Another plugin which i installed with .deb packages are working. 

I'm using the the git repository (with every commit). The version 1.1 is now 1 1/2 years old.

**Comment by mcost** [comment]
hi Roger,

 
Perhaps try the version 1.0? that's the one I am using on Fedora and it works, I haven't tried any later ones yet.

 
Other than this I really don't know... Last time I had problems with the zarafa files plugin on Webapp that wasn't showing up, in the end I think the issue was some php package that I did not install as a dependency.

 
Marco


 
-----Original message-----

**Comment by RogerSik** [comment]
﻿Hi,



i tried it now with 1.1 and with 1.1 the options are available.

**Comment by mcost** [comment]
great, so it's fine.

 
Not sure wha'ts wrong with the other. I will upgrade mine when I get the chance as well.

 
Marco


 
-----Original message-----

**Comment by RogerSik** [comment]
﻿Thanks for your help. :-)



Are there plans to release 1.2?

**Comment by mcost** [comment]
I have no idea, I am just a user like you :)

 
Marco


 
-----Original message-----

**Comment by RogerSik** [comment]
Hi,

under the folder b"uilds" in the directory i found the release passwd-1.2 which works very good and I can recommend when someone want to have the newest version.

https://github.com/silentsakky/zarafa-webapp-passwd/blob/master/builds/passwd-1.2.zip

**Comment by mcost** [comment]
Thank you. 

Marco

On 29 September 2015 20:23:51 BST, Roger <notifications@github.com> wrote:
>Hi,
>
>under the folder b"uilds" in the directory i found the release
>passwd-1.2 which works very good and I can recommend when someone want
>to have the newest version.
>
>https://github.com/silentsakky/zarafa-webapp-passwd/blob/master/builds/passwd-1.2.zip
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/silentsakky/zarafa-webapp-passwd/issues/12#issuecomment-144162499
>-- 
>This message has been scanned for viruses and
>dangerous content by MailScanner, and is
>believed to be clean.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.
