### ISSUE TITLE
Difference between master and ./builds/passwd-1.2.zip

### ISSUE THREAD

**Issue by micressor** [silentsakky/zarafa-webapp-passwd#15]
Install guide (clone git repo) into plugins directory does not work for me. Plugin does not show up in the webapp gui.

Installed from  zip file [passwd-1.2.zip](https://github.com/silentsakky/zarafa-webapp-passwd/blob/master/builds/passwd-1.2.zip) works fine.

It looks like a difference between latest master commit and the  zip file [passwd-1.2.zip](https://github.com/silentsakky/zarafa-webapp-passwd/blob/master/builds/passwd-1.2.zip).

> diff -r passwd-zip/ passwd-git/
> Only in passwd-git/: builds
> Only in passwd-git/: build.xml
> Only in passwd-git/: CHANGELOG.md
> Only in passwd-git/: .git
> Only in passwd-git/js: ABOUT.js
> Only in passwd-git/js: data
> Only in passwd-git/js: external
> Only in passwd-zip/js: passwd-debug.js
> Only in passwd-zip/js: passwd.js
> Only in passwd-git/js: PasswdPlugin.js
> Only in passwd-git/js: settings
> Only in passwd-zip/language/de_DE.UTF-8/LC_MESSAGES: plugin_passwd.mo
> Only in passwd-git/language/de_DE.UTF-8/LC_MESSAGES: plugin_passwd.po
> Only in passwd-git/language: hu_HU.UTF-8
> Only in passwd-zip/language/nl_NL.UTF-8/LC_MESSAGES: plugin_passwd.mo
> Only in passwd-git/language/nl_NL.UTF-8/LC_MESSAGES: plugin_passwd.po
> Only in passwd-git/: LICENSE
> Only in passwd-git/: README.md
> Only in passwd-zip/resources/css: passwd.css
> Only in passwd-git/resources/css: passwd-main.css
> Only in passwd-git/resources/images: icon_lock.xcf

**Comment by silentsakky** [comment]
Yes there are lots of differences in master version which is not released
yet as it is not properly tested yet

On Mon, May 16, 2016 at 4:55 PM, Marco Balmer <notifications@github.com>
wrote:

> Install guide (clone git repo) into plugins directory does not work for
> me. Plugin does not show up in the webapp gui.
>
> Installed from zip file passwd-1.2.zip
> <https://github.com/silentsakky/zarafa-webapp-passwd/blob/master/builds/passwd-1.2.zip>
> works fine.
>
> It looks like a difference between latest master commit and the zip file
> passwd-1.2.zip
> <https://github.com/silentsakky/zarafa-webapp-passwd/blob/master/builds/passwd-1.2.zip>
> .
>
> diff -r passwd-zip/ passwd-git/
> Only in passwd-git/: builds
> Only in passwd-git/: build.xml
> Only in passwd-git/: CHANGELOG.md
> Only in passwd-git/: .git
> Only in passwd-git/js: ABOUT.js
> Only in passwd-git/js: data
> Only in passwd-git/js: external
> Only in passwd-zip/js: passwd-debug.js
> Only in passwd-zip/js: passwd.js
> Only in passwd-git/js: PasswdPlugin.js
> Only in passwd-git/js: settings
> Only in passwd-zip/language/de_DE.UTF-8/LC_MESSAGES: plugin_passwd.mo
> Only in passwd-git/language/de_DE.UTF-8/LC_MESSAGES: plugin_passwd.po
> Only in passwd-git/language: hu_HU.UTF-8
> Only in passwd-zip/language/nl_NL.UTF-8/LC_MESSAGES: plugin_passwd.mo
> Only in passwd-git/language/nl_NL.UTF-8/LC_MESSAGES: plugin_passwd.po
> Only in passwd-git/: LICENSE
> Only in passwd-git/: README.md
> Only in passwd-zip/resources/css: passwd.css
> Only in passwd-git/resources/css: passwd-main.css
> Only in passwd-git/resources/images: icon_lock.xcf
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/silentsakky/zarafa-webapp-passwd/issues/15>
>



-- 
My Email Addresses:-
      s <s.patel@zarafa.com>aket.d.patel@gmail.com
      saket.patel@yahoo.com

**Comment by silentsakky** [comment]
Have released a new version containing all changes, please check with latest version

https://github.com/silentsakky/zarafa-webapp-passwd/releases
