### ISSUE TITLE
Kopano WebApp 3.1.0 supported?

### ISSUE THREAD

**Issue by WalterHof** [silentsakky/zarafa-webapp-passwd#16]
Hi,

Is Kopano WebApp 3.1.0 supported?
I downloaded and installed the plugin (v 1.2) but this plugins is not visible under plugins on the web interface.

Walter

**Comment by smhswiss** [comment]
Hi Walter

I just installed version 1.2 with Kopano Webapp 3 and it works as it should from my point.
But you need to unzip the version located under the builds folder.

Kind regards
Stefan

**Comment by WalterHof** [comment]
Hi Stefan,

Thank you, there was a error in my configuration, fortunately it works now. 

Regards Walter


Von meinem iPhone gesendet

Am 23.02.2017 um 14:55 schrieb Stefan M. Haller <notifications@github.com <mailto:notifications@github.com> >:

Hi Walter

I just installed version 1.2 with Kopano Webapp 3 and it works as it should from my point.
But you need to unzip the version located under the builds folder.

Kind regards
Stefan
