### ISSUE TITLE
tag 1.2 missing in github repository

### ISSUE THREAD

**Issue by qyanu** [silentsakky/zarafa-webapp-passwd#19]
Hello,

i noticed, that this github repository does not publish a tag for version 1.2.
please consider my request to publish the tag at the appropriate commit, as was used to build the version 1.2 downloadable at the zarafa community hub.

with kind regards,
Max-Julian Pogner

**Comment by silentsakky** [comment]
version 1.2 was never formally released in zarafa community, so I had not created tag for that

**Comment by silentsakky** [comment]
https://github.com/silentsakky/zarafa-webapp-passwd/releases/tag/1.2
