### ISSUE TITLE
Works v1.3 with WebApp 3.4.0?

### ISSUE THREAD

**Issue by nils50122** [silentsakky/zarafa-webapp-passwd#20]
hello,

i extract the folder passwd-1.3.zip in my webapp/plugins/, restart apache2 and load the site with new cache but i dont see the plugin under settings.

Is the strucuture the right?
Now i have the folders /webapp/plugins/passwd-1.3/js
/webapp/plugins/passwd-1.3/php
/webapp/plugins/passwd-1.3/resources
/webapp/plugins/passwd-1.3/config.php
/webapp/plugins/passwd-1.3/manifest.xml

**Comment by silentsakky** [comment]
plugin name should be passwd not passwd-1.3

**Comment by nils50122** [comment]
@silentsakky, that was not the solution.

**Comment by silentsakky** [comment]
Below are some debugging steps which can help understand problem

1) make sure plugin is extracted in proper place, for ubuntu 16 it is /usr/share/kopano-webapp/plugins
2) check if passwd and all files/folders under that is accessible by apache ie permission is set properly
3) check apache log for any php errors in loading plugin
4) check if passwd.js and passwd.css files are getting loaded when loading webapp, this can be checked in developer tools

**Comment by silentsakky** [comment]
No updates, so closing this
